baseURL = 'https://recipes.stegeman.me/'
languageCode = 'en-us'
title = 'Recipes'
theme = 'simple'

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 1

[[menu.main]]
name = "Archive"
url = "/archive/"
weight = 2

[taxonomies]
  tag = "tags"
